#!/bin/sh
# $Id$
# copyright (C) 2004 Topia <topia@clovery.jp>. all rights reserved.

THISDIR="${THISDIR-$(dirname $0)}"
[ "0${DEBUG}" -ge 1 ] && echo "${THISDIR}/main: start"
[ "0${DEBUG}" -ge 2 ] && echo "${THISDIR}/main: read tiarrarc"
[ -f "${THISDIR}/.tiarrarc" ] && . "${THISDIR}/.tiarrarc"
if [ -f "${THISDIR}/.tiarrarc-once" ]; then
  . "${THISDIR}/.tiarrarc-once"
  rm -f "${THISDIR}/.tiarrarc-once"
fi

WORKDIR=${WORKDIR:-$(dirname $0)}
if [ -z "${TOPDIR}" ]; then
  TOPDIR=.
else
  TOPDIR="${TOPDIR}/.."
fi
PERL=${PERL:-/usr/opt/bin/perl}
PERLARG=${PERLARG:--wt}
TIARRA=${TIARRA:-${TOPDIR}/tiarra}
CONF=${CONF:-tiarra.conf}
REDIR_STDOUT=${REDIR_STDOUT:-errlog.stdout}
REDIR_STDERR=${REDIR_STDERR:-errlog.stderr}
DAEMON_MODE=${DAEMON_MODE:-yes}

if [ \! -z "${DEBUG}" ]; then
  echo "    configuration"
  echo "workdir: ${WORKDIR}"
  echo "perl   : ${PERL}"
  echo "perlarg: ${PERLARG}"
  echo "tiarra : ${TIARRA}"
  echo "config : ${CONF}"
  echo "extra  : $@"
  echo "stdout : ${REDIR_STDOUT}"
  echo "stderr : ${REDIR_STDERR}"
  echo "daemon : ${DAEMON_MODE}"
else
  cd "${WORKDIR}"
  if [ "X${DAEMON_MODE}" = "Xyes" ]; then
    ${PERL} ${PERLARG} ${TIARRA} "--config=${CONF}" "$@" >>"${REDIR_STDOUT}" 2>>"${REDIR_STDERR}" <&- &
  else
    exec ${PERL} ${PERLARG} ${TIARRA} "--config=${CONF}" "$@" >>"${REDIR_STDOUT}" 2>>"${REDIR_STDERR}" <&-
  fi
fi
