#!/bin/sh
# $Id$
# copyright (C) 2004 Topia <topia@clovery.jp>. all rights reserved.

THISDIR="${THISDIR-$(dirname $0)}"
[ "0${DEBUG}" -ge 1 ] && echo "${THISDIR}/subr: start"
[ "0${DEBUG}" -ge 2 ] && echo "${THISDIR}/subr: read tiarrarc"
[ -f "${THISDIR}/.tiarrarc" ] && . "${THISDIR}/.tiarrarc"
if [ -f "${THISDIR}/.tiarrarc-once" ]; then
  . "${THISDIR}/.tiarrarc-once"
  rm -f "${THISDIR}/.tiarrarc-once"
fi

# override
WORKDIR="${WORKDIR:-${THISDIR}}"
if [ -z "${TOPDIR}" ]; then
  TOPDIR=.
else
  TOPDIR="${TOPDIR}/.."
fi

THISDIR="${THISDIR}/.."
. "${THISDIR}/run"
